### ISSUE TITLE
Typed property YusufKandemir\MicrodataParser\MicrodataDOMDocument::$xpath must not be accessed before initialization

### ISSUE THREAD

**Issue by joshua-bn** [yusufkandemir/microdata-parser#4]
## Detailed description

```
Typed property YusufKandemir\MicrodataParser\MicrodataDOMDocument::$xpath must not be accessed before initialization
```
This happens when you use `fromDOMDocument()`

Using `loadHTML()` and `loadHTMLFile()` don't have this issue because they set $xpath. Needs a way to set $xpath outside of those methods.

**Comment by yusufkandemir** [comment]
Thanks for reporting 👏 Fixed in https://github.com/yusufkandemir/microdata-parser/releases/tag/v1.0.1
